path: "C:\\Users\\79053\\Desktop\\image"
userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
referrer: "https://www.google.com"
htmlTag: "img"
attribute: "abs:src"